# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Iljoong's Blog
email: iljoong@outlook.com
description: > # this means to ignore newlines until "baseurl:"
 Blog about Cloud, Modern App Development and Trends
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://iljoong.github.io/" # the base hostname & protocol for your site
twitter_username: iljoongk
github_username:  iljoong

# Build settings
markdown: kramdown
